import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { format } from "date-fns";
import type { GrvDetail } from "@/hooks/use-grvs";

const styles = StyleSheet.create({
  page: {
    padding: 24,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#1e293b",
    backgroundColor: "#ffffff",
  },
  title: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  box: {
    width: "48%",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 8,
  },
  sectionTitle: {
    fontSize: 9,
    fontWeight: 700,
    textTransform: "uppercase",
    marginBottom: 4,
    color: "#64748b",
  },
  line: { marginBottom: 2 },
  table: { marginTop: 10, borderWidth: 1, borderColor: "#e2e8f0" },
  headerRow: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    padding: 6,
  },
  bodyRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    padding: 6,
  },
  c1: { width: "12%", fontSize: 8 },
  c2: { width: "40%" },
  c3: { width: "12%", textAlign: "right" },
  c4: { width: "16%", textAlign: "right" },
  c5: { width: "20%", textAlign: "right", fontWeight: 700 },
  totals: {
    marginTop: 10,
    marginLeft: "55%",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 8,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  footer: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 8,
    color: "#64748b",
    fontSize: 8,
  },
});

export function GrvPdfDocument({
  grv,
  company,
}: {
  grv: GrvDetail;
  company: any;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Goods Received Voucher</Text>

        <View style={styles.row}>
          <View style={styles.box}>
            <Text style={styles.sectionTitle}>Supplier</Text>
            <Text style={styles.line}>{grv.supplierName || "N/A"}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.sectionTitle}>Document Info</Text>
            <Text style={styles.line}>GRV No: {grv.grvNumber}</Text>
            <Text style={styles.line}>
              Date:{" "}
              {grv.createdAt
                ? format(new Date(grv.createdAt), "dd/MM/yyyy HH:mm")
                : "-"}
            </Text>
            <Text style={styles.line}>
              Recorded By: {grv.createdBy || "System"}
            </Text>
          </View>
        </View>

        <View style={styles.row}>
          <View style={styles.box}>
            <Text style={styles.sectionTitle}>Received By</Text>
            <Text style={styles.line}>
              {company?.tradingName || company?.name || "Company"}
            </Text>
            <Text style={styles.line}>{company?.address || "-"}</Text>
            <Text style={styles.line}>
              {company?.city || ""} {company?.country || ""}
            </Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.sectionTitle}>Notes</Text>
            <Text>{grv.notes || "-"}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.c1}>SKU</Text>
            <Text style={styles.c2}>Description</Text>
            <Text style={styles.c3}>Qty</Text>
            <Text style={styles.c4}>Unit Cost</Text>
            <Text style={styles.c5}>Line Total</Text>
          </View>
          {grv.lines.map((line) => (
            <View key={line.id} style={styles.bodyRow}>
              <Text style={styles.c1}>{line.sku || "-"}</Text>
              <Text style={styles.c2}>{line.productName}</Text>
              <Text style={styles.c3}>{line.quantity.toFixed(2)}</Text>
              <Text style={styles.c4}>${line.unitCost.toFixed(2)}</Text>
              <Text style={styles.c5}>${line.totalCost.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.totals}>
          <View style={styles.totalRow}>
            <Text>Total Qty</Text>
            <Text>{grv.totalQuantity.toFixed(2)}</Text>
          </View>
          <View style={[styles.totalRow, { marginBottom: 0 }]}>
            <Text style={{ fontWeight: 700 }}>Total Cost</Text>
            <Text style={{ fontWeight: 700 }}>${grv.totalCost.toFixed(2)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by {company?.tradingName || company?.name || "System"} | GRV{" "}
          {grv.grvNumber}
        </Text>
      </Page>
    </Document>
  );
}
