<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>FiscalStackPOS</AssemblyName>
    <RootNamespace>FiscalStackPOS</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>fiscalstack.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="fiscalstack.png" />
    <Resource Include="fiscalstack.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="FiscalStack">
      <HintPath>..\..\REVMAX\FiscalStack_NoDevice\Deploy\FiscalStack.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\REVMAX\FiscalStack_NoDevice\Deploy\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="QRCoder">
      <HintPath>C:\Users\TIMIRE\.nuget\packages\qrcoder\1.8.0\lib\net40\QRCoder.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>