// Global expense categories shared by desktop (web) and mobile apps.
// Kept as a single source of truth so category naming stays consistent
// across platforms, reports and the chart of accounts.
export const EXPENSE_CATEGORIES = [
  // General / legacy
  "Rent",
  "Utilities",
  "Salary",
  "Marketing",
  "Equipment",
  "Inventory Purchase",
  "Software",
  "Taxes",
  "Legal & Professional",
  "Travel",
  "Other",
  // Operating expenses
  "Salaries and wages",
  "Overtime",
  "Casual workers",
  "Medical aid",
  "Staff welfare",
  "Uniforms / PPE",
  "Advertising",
  "Stationery",
  "Courier services",
  "Tea + lunch provisions",
  "Cleaning materials",
  "Licenses & permits",
  "Fuel",
  "Vehicle insurance",
  "Vehicle maintenance / service",
  "Vehicle tracking",
  "Tolls / Targets",
  "Local travel",
  "Transport hiring",
  "Parking",
  "Accommodation",
  "Airtime",
  "Data / Wi-Fi",
  "Landline bills",
  "Stock purchase / Raw materials",
  "Packaging",
  "Stock losses / shrinkage",
  "Cash shortage",
  "Equipment repair",
  "Generator expenses",
  "Service providers",
  "CCTV / Security",
  "Bank / EcoCash charges",
  "Fines and penalties",
  "Donations",
  "Entertainment",
] as const;